language: go
go:
- 1.8.x
install:
- go get -v github.com/spf13/hugo
script:
- hugo
- python --version
- sudo pip install s3cmd
- s3cmd sync --delete-removed --access_key=${AWS_ACCESS_KEY} --secret_key=${AWS_SECRET_KEY} -M -f -r publish/
  s3://rprakashg-io-web/
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: P8Fg7Ygw/y5af11O16VCbK0dyPOw2RJQaW+XdHoc/rgn26LzOrWwtmGiXG2AcY3t+8I1giefWJikiiugDGAmpScs5a3/Te/VN3MRTT8NAT6iwg8WBUxLtWPmqIuSHnXVuvvRKI1TDsF4fDrFhyrGZ8I3ptlurWa93KhoNC1VVENVicaFMgDyxlXeWqAEuV1yDUa0uPGA8KWnUIdDfiXV95PwhDZelH2YApOgJv1H7+26V2lL2pC31ISI2CsmntCTMAvwgCeHNLJICNC8gaekjlEAwHc1lwdR1NtjIVNfmWWExKBhDuiDuTws6sO0bbdAvlAUFNnfnhE0vzlZMPNIovCYYfp+wHkt/hMfXv56QvklexH0pWItDC8eJfy7DJMosKI0eT9Sbt8Ky2k2NNhHoi4sO8URAqni9sIj5CcEDy/jNMZGQIvQZ8L6T/2wEyvvPK/YkLHThrJ77238ESHavlZ0gqaBis3DFMYGID0HUte2mqtbuLsUTOWXk+YesOekYLgMBqjeb/mTbxnSp4GW6fAbHd6eGBtFqJWxGh4NU4kshlweY6fOwxV5rt2pIbMch+fWsBKY5UtC22qVTQ4jv3DbcOABz3kQNatCZ+9Fa2h2RD1rCI+ajOqqVgsJc+EhsbnqRJ9oUla7ZquIy6XkvCSF+H5DVnBrKaBVyS645eQ=
  - secure: Jj2bnh29H0XnmnBPkA8Qhtt7QtxZoJJedDBEtwkvk8FiCaHqdhNqX40zK1Y5mCn9ymsUHJVBLTRZI80/RpZKZxWnHQNgtehTQS4OD+TkMVQUfQ72Td/jpqBv5QiIJLfFeplUZhJtbKnQBLVecC4l+PI3gaV6GtiN75oVWgCXnF7KJdoeIDnIJI1j4fmqdleET2x9XIXc21jltrydoZPRWFv42ika+edkYtxc6/G08afOIOIUzHw7sTFbb+fGrvWe7Akd7BqnIfeRuwB5VD9faDGuMKDIZL7oyndL/o2i71HSGwE+P0TUrDE4t7iB07LeoHw8fvNp7Kcn5GPyo5/puQumdbBonkn+KFyKriQjI0bK+vkXOHBz3ezJLzV53vtyNtRS2yYRFsYDW6ikwYyp75AUqynwxnl9YBS7QglwC0GHk6dA9okjUsSZgkwoUB4PRLBPOiTpr/QMxoVBtiWtle5bC3SqxIBygRCxrd5DDQHwqAwrYd3gFzwzjexV3B8Y1usJT14SDdfZJzl6FJzjqPysyvrCYX3OgmrVDHX6Y3d2AfVBWQhznNBNtn2Lwu8aaOYZKHiunXlE4mXjDcrfZ2x9oswXACPkM45PScKiMVw2n4BRaij2S9lptNHRKeM8bWSkGuvlv/dc2nsnWkzxOS0kVdTlwUHt2P70PVAHIKU=
