baseurl = "http://rprakashg.io/"
languageCode = "en-us"
title = "Ram Gopinathan's Resume"
theme = "hugo-orbit"
googleAnalytics = "UA-20393691-6"
contentdir = "content"
layoutdir = "layouts"
publishdir = "publish"
dataDir = "data"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Ram Gopinathan's Resume"
    author = "Ram Gopinathan"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ram Gopinathan"
        tagline = "Full Stack Web and Mobile Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: rprakashg@gmail.com"
        title = "rprakashg@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+3125208046"
        title = "+3125208046"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "http://rprakashg.io/blog"
        title = "rprakashg.io/blog"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "http://linkedin.com/in/rprakashg"
        title = "rprakashg"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "http://github.com/rprakashg"
        title = "rprakashg"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/dad2lnl"
        title = "dad2lnl"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelors degree"
        college = "University of Calicut"
        dates = "1990 - 1994"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Running"

        [[params.interests.list]]
        interest = "Golfing"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Principal Architect** with over 22+ years of experience in the software industry. Primarily focused on Docker, Microservices, AWS/Azure cloud and DevOps and Continuous Delivery"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Sr. Manager/Principal Architect"
        dates = "Jan 2016 - Present"
        company = "T-Mobile, Bellevue"
        details = "As a Principal Architect working primarily on T-Mobile web properties as well as mobile apps that leverage AWS cloud. Design, build, test dockerized microservices that run on Mesos/Marathon, Continous Delivery using Jenkins, Artifactory"

        [[params.jobs.list]]
        position = "Full Stack Engineer (Contract)"
        dates = "Oct 2015 - Dec 2015"
        company = "Microsoft, Redmond"
        details = "As a full stack engineer worked on hybrid cloud employee data management solution for Microsoft HRIT. Application is used by all employees of Microsoft and automates several business processes for Microsoft HR group by providing an easy to use modern web based user interface. Technologies utilized include Azure Cloud Services, Azure Servicebus, AngularJS, KnockoutJS, Less/Sass, ASP.NET MVC/Web API, WCF services, K2 for workflow automation and Octopus Deploy for automating Azure deployment."

        [[params.jobs.list]]
        position = "Full Stack Engineer (Contract)"
        dates = "Aug 2015 - Oct 2015"
        company = "Visa, Bellevue"
        details = "Worked as a Contract full stack engineer on Authorize.Net payment platform for Visa. Authorize.NET platform provides APIs and tools necessary for business to perform credit card transactions on the web. Worked on a key project that completely built the user experience platform from the ground up to provide a responsive, modern web application experience that works well on all form factors. Leverage AngularJS, Less/SaaS, Gulp, Bootstrap on the front end and ASP.NET Web API for developing backend APIs that power web experiences."

        [[params.jobs.list]]
        position = "Cloud Solutions Architect/Trainer"
        dates = "Dec 2014 - Jan 2017"
        company = "Marview Solutions, Redmond"
        details = "As an Independant Cloud Solution Architect was primarily focused on consulting and training on Azure cloud platform for customers around the globe"

        [[params.jobs.list]]
        position = "Technical Lead"
        dates = "Nov 2013 - Dec 2014"
        company = "Bluetooth SIG, Kirkland"
        details = "Member of engineering team, responsible for design, development of internal and public facing online websites, tools and applications for Bluetooth primarily on Microsoft platform"

        [[params.jobs.list]]
        position = "Senior Service Design Engineer"
        dates = "June 2012 - Sept 2013"
        company = "Microsoft, Redmond"
        details = "As a Sr. SDE within the Microsoft.com team, key responsibilities include design build online consumer facing websites and services deployed on Microsoft.com ECM platform."

        [[params.jobs.list]]
        position = "Solutions Architect (Contract)"
        dates = "Dec 2011 - May 2012"
        company = "Deloitte Tax, Dallas"
        details = "As SharePoint Solutions Architect worked on global tax portal project developed on SharePoint 2010 platform. Tax Portal automates all tax mega processes and is used by Deloitte tax professionals all around the world"

        [[params.jobs.list]]
        position = "Solutions Architect (Contract)"
        dates = "July 2011 - Dec 2011"
        company = "Federal Reserve Bank, Chicago"
        details = "As SharePoint Solutions Architect worked on migration/Re-Design of intranet portal built using autonomy team site and other various open source CMS platforms to SharePoint 2010 platform."

        [[params.jobs.list]]
        position = "Sr. Manager"
        dates = "Oct 2010 - April 2011"
        company = "Deloitte, Chicago"
        details = "As a Sr. Manager based out of Chicago is responsible for design and architecture of Deloitte next generation extranet platform on SharePoint 2010. Leading migration activities for about 90,000 eRoom sites and 30TB of content as well as development of new capabilities in SharePoint 2010. Responsibilities also include working cross teams with Intranet & Knowledge Management and Enterprise Search initiatives. Working with offshore partners assisting in design review as well as overseeing delivery of key software components."

        [[params.jobs.list]]
        position = "Solutions Architect"
        dates = "Mar 2008 - Sept 2010"
        company = "Microsoft, Chicago"
        details = "As a SharePoint Architect based out of central region worked on SharePoint projects for Large global enterprise customers."


    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Listed below are few of the projects opensourced on github"

        [[params.projects.list]]
        title = "Cloudformation Templates"
        url = "https://github.com/rprakashg/cf-templates"
        tagline = "AWS Cloudformation templates contributed to community"

        [[params.projects.list]]
        title = "Generic Repository Implementation for AWS SQS & S3"
        url = "https://github.com/rprakashg/aws-common"
        tagline = "Java/SpringBoot library that implements generic repository for AWS S3 and SQS"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Docker"
        level = "90%"
                
        [[params.skills.list]]
        skill = "Microservices"
        level = "98%"

        [[params.skills.list]]
        skill = "Docker Swarm & Mesos/Marathon"
        level = "98%"

        [[params.skills.list]]
        skill = "SpringBoot & SpringCloud"
        level = "80%"

        [[params.skills.list]]
        skill = "Java & C#"
        level = "95%"

        [[params.skills.list]]
        skill = "Golang"
        level = "60%"

        [[params.skills.list]]
        skill = "NodeJS"
        level = "70%"

        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "75%"

        [[params.skills.list]]
        skill = "API First & API Design"
        level = "80%"

    # Footer section
    [params.footer]
        copyright = "Ram Gopinathan, all rights reserved"